library(data.table)
sampledata <- fread("household_power_consumption.txt",nrows = 100, na.strings = "?")
#classes<-sapply(sampledata,class)
#fulldata<-fread("household_power_consumption.txt", na.strings = "?",colClasses = classes)
#subdata<-subset(fulldata,fulldata$Date %in% c("2/2/2007","1/2/2007"))
subdata1<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),sep = ";",na.strings = "?")
names(subdata1)<-names(sampledata)
hist(subdata1$Global_active_power,main="Global Active Power",xlab = "Global Active Power(Kilowatts)",col="RED")
dev.copy(png,file="plot1.png")
dev.off()