library(data.table)
sampledata <- fread("household_power_consumption.txt",nrows = 100, na.strings = "?")
#classes<-sapply(sampledata,class)
#fulldata<-fread("household_power_consumption.txt", na.strings = "?",colClasses = classes)
#subdata<-subset(fulldata,fulldata$Date %in% c("2/2/2007","1/2/2007"))
subdata1<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),sep = ";",na.strings = "?")
names(subdata1)<-names(sampledata)
#hist(subdata1$Global_active_power,main="Global Active Power",xlab = "Global Active Power(Kilowatts)",col="RED")
library(dplyr)
subdata1<- mutate(subdata1,DateF = as.Date(Date,format("%d/%m/%Y")))
#class(subdata1$DateF)
subdata1$TMSTP<- strptime(paste(subdata1$Date,subdata1$Time),"%d/%m/%Y %H:%M:%S")
#class(subdata1$TMSTP)
par(mfrow=c(2,2))
with(subdata1, 
   {
plot(subdata1$TMSTP,subdata1$Global_active_power,type = 'l',xlab = "", ylab = "Global Active Power(Kilowatts)")
plot(subdata1$TMSTP,subdata1$Voltage,type = 'l',xlab = "datetime", ylab = "Voltage")
plot(subdata1$TMSTP,subdata1$Sub_metering_1,type = 'n',xlab = "", ylab = "Energy Sub Metering")
lines(subdata1$TMSTP,subdata1$Sub_metering_1,col = "black")
lines(subdata1$TMSTP,subdata1$Sub_metering_2,col = "red")
lines(subdata1$TMSTP,subdata1$Sub_metering_3,col = "blue")
legend("topright",lty = 1,bty = "n",lwd = 1,col=c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(subdata1$TMSTP,subdata1$Global_reactive_power,type = 'l',xlab = "datetime", ylab = "Global Reactive Power")
})
dev.copy(png,file="plot4.png")
dev.off()
